apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: coordinator
spec:
  scaleTargetRef: {apiVersion: apps/v1, kind: Deployment, name: coordinator}
  minReplicas: 3
  maxReplicas: 50
  behavior:
    scaleUp: {stabilizationWindowSeconds: 0, policies: [{type: Percent, value: 100, periodSeconds: 60}]}
    scaleDown: {stabilizationWindowSeconds: 300, policies: [{type: Percent, value: 25, periodSeconds: 60}]}
  metrics:
    - type: Resource
      resource: {name: cpu, target: {type: Utilization, averageUtilization: 65}}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker
spec:
  scaleTargetRef: {apiVersion: apps/v1, kind: Deployment, name: worker}
  minReplicas: 10
  maxReplicas: 2000
  behavior:
    scaleUp: {stabilizationWindowSeconds: 0, policies: [{type: Pods, value: 100, periodSeconds: 60}]}
    scaleDown: {stabilizationWindowSeconds: 600, policies: [{type: Percent, value: 10, periodSeconds: 60}]}
  metrics:
    - type: Resource
      resource: {name: cpu, target: {type: Utilization, averageUtilization: 70}}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: analyzer
spec:
  scaleTargetRef: {apiVersion: apps/v1, kind: Deployment, name: analyzer}
  minReplicas: 3
  maxReplicas: 100
  metrics:
    - type: Resource
      resource: {name: cpu, target: {type: Utilization, averageUtilization: 65}}
