apiVersion: v1
kind: ServiceAccount
metadata:
  name: opa-guard-coordinator
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opa-guard-worker
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opa-guard-analyzer
automountServiceAccountToken: false
